import com.gtnewhorizons.gtnhgradle.tasks.RunHotswappableMinecraftTask;

compileJava.options.encoding = "UTF-8"

eclipse {
    jdt {
        file {
            withProperties {props ->
                props.setProperty(
                    "org.eclipse.jdt.core.compiler.compliance",
                    "1.8"
                )
            }
        }
    }
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

checkstyle {
    toolVersion = "13.8.0"
}

minecraft {
    injectedTags.put("MOD_ID", modId)
    injectedTags.put("MOD_NAME", modName)
    injectedTags.put("MOD_VERSION", modVersion)
    injectedTags.put("MOD_DEPENDENCIES", modDependencies)
}

tasks.withType(RunHotswappableMinecraftTask) {
    extraJvmArgs = []
    if (new Boolean(project.findProperty("disableMixinValidation"))) {
        extraJvmArgs.addAll([
            "-Dmixin.debug=true",
            "-Dmixin.debug.verbose=true",
            "-Dmixin.env.ignoreRequired=true"
        ])
    }
    if (new Boolean(project.findProperty("enableDebugMCLogging"))) {
        extraJvmArgs.addAll(["-Dlog4j.configurationFile=file://${new File(project.projectDir, "log4j2-debug.xml").absolutePath}"])
    }
}

publishing {
    repositories {
        maven {
            name = "GitHub-Packages"
            url = uri("https://maven.pkg.github.com/glektarssza/minecraft-gtnh-customizer")
            credentials {
                username = project.findProperty("ghpr.user") ?: System.getenv("GHPR_USERNAME")
                password = project.findProperty("ghpr.key") ?: System.getenv("GHPR_TOKEN")
            }
        }
    }
}
