# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
  workflow_call:
    inputs:
      ref:
        description: |
          The Git reference from which to build the project.

          Defaults to the reference that caused the workflow to be invoked or
          the default branch if no reference is available.
        type: string
        required: false
        default: ${{github.ref || github.event.repository.default_branch}}
    outputs:
      artifacts-id:
        description: |
          The ID of the generated artifacts.
        value: ${{jobs.build.outputs.artifacts-id}}
      artifacts-url:
        description: |
          The URL from which the generated artifacts can be downloaded.
        value: ${{jobs.build.outputs.artifacts-url}}
    secrets:
      github-token:
        description: |
          The token to use when making authenticated calls to the GitHub API.
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      #-- To clone repository
      contents: read
    outputs:
      artifacts-id: ${{steps.upload-artifacts.outputs.artifact-id}}
      artifacts-url: ${{steps.upload-artifacts.outputs.artifact-url}}
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{inputs.ref}}
          lfs: true
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v4
        with:
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
          distribution: temurin
          java-version-file: .java-version
      - id: setup-gradle
        name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
      - id: setup-ci-workspace
        name: Setup CI Workspace
        run: ./gradlew setupCIWorkspace
      - id: build
        name: Build
        run: ./gradlew build
      - id: upload-artifacts
        name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: build/libs/
          compression-level: 0
          if-no-files-found: error
