# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Manual Publish
on:
  workflow_dispatch:
    inputs:
      github-release-id:
        description: |
          The GitHub release ID to attach the artifacts to.

          Only required when `attach-to-github-release` is `true`.
        type: string
        required: false
        default: ""
      attach-to-github-release:
        description: |
          Whether to attach the released assets to a GitHub release.

          Useful when testing other parts of the publish workflow.

          Defaults to `false`.
        type: boolean
        required: false
        default: false
      java-vendor:
        description: |
          The Java vendor to use.

          Defaults to `temurin`.
        type: choice
        required: false
        options:
          - temurin
          - zulu
          - adopt
          - adopt-hotspot
          - adopt-openj9
          - liberica
          - microsoft
          - corretto
          - semeru
          - oracle
          - dragonwell
          - sapmachine
          - graalvm
          - jetbrains
        default: temurin
      java-version:
        description: |
          The Java version to use.

          Defaults to `version-file` to use the version found in the
          `.java-version` file present in the project.
        type: string
        required: false
        default: version-file
      gradle-version:
        description: |
          The Gradle version to use.

          Defaults to `wrapper` to use version of the Gradle wrapper present in
          the project.
        type: string
        required: false
        default: wrapper
      artifact-retention-days:
        description: |
          The duration, in days, to retain artifacts for.

          Defaults to `0` which defaults to the value configured for the
          repository.
        type: number
        required: false
        default: 0
jobs:
  publish:
    name: Publish
    permissions:
      #-- To clone repository
      contents: read
      #-- To uploads packages
      packages: write
    uses: ./.github/workflows/publish.yaml
    with:
      ref: ${{github.sha}}
      github-release-id: ${{inputs.github-release-id}}
      attach-to-github-release: ${{inputs.attach-to-github-release}}
      java-version: ${{inputs.java-version}}
      java-vendor: ${{inputs.java-vendor}}
      gradle-version: ${{inputs.gradle-version}}
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
